# Generated by Django 3.0.2 on 2020-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='numb_of_true_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='bool_answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
