# Generated by Django 3.0.2 on 2020-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200130_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numb_of_true_answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
