# Generated by Django 3.0.2 on 2020-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourchoice',
            name='numb_of_option4',
        ),
        migrations.AddField(
            model_name='fourchoice',
            name='true_answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
